image: ubuntu:22.04

stages:
  - build

build-and-test:
  stage: build
  script:
    - apt-get update && apt-get install -y make libturbojpeg git
    - apt-get install -y python3.10 python3-pip build-essential libssl-dev libffi-dev python3-dev python3.10-venv
    - make DEVICE=cpu install_all
    - make ci_static_code_analysis
    - make ci_test
